/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e75197f06e8563f32296087
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examBaseService PLEASE EDIT ../exam.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exam } from '../../domain/test_skaffolder_db/exam';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../exam.service.ts
 */

/*
 * SCHEMA DB exam
 *
	{
		place: {
			type: 'String'
		},
		score: {
			type: 'Number'
		},
		valid: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_course: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_student: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_teacher: {
			type: Schema.ObjectId,
			ref : "exam"
		},
	}
 *
 */
@Injectable()
export class ExamBaseService {

    contextUrl: string = environment.endpoint + '/exam';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * examService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * examService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * examService.findBy_course
    *   @description CRUD ACTION findBy_course
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_course(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_course/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examService.findBy_teacher
    *   @description CRUD ACTION findBy_teacher
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_teacher(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Exam> {
        return this.http
            .get<Exam>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * examService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * examService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs


    /**
    * examService.sayHello
    *   @description Say Hello
    *
    */
    sayHello(...params: any[]): Observable<any> {
        return this.http
            .get<any>(this.contextUrl + '/action/hello', {})
            .pipe(
                map(response => response)
            );
    }


    /**
    * examService.validate
    *   @description This API is used to validate the exam
    *   @param String id id of the exam
    *   @returns Boolean
    *
    */
    validate(...params: any[]): Observable<any> {
        return this.http
            .post<any>(this.contextUrl + '/{id}/validate', {})
            .pipe(
                map(response => response)
            );
    }

}
